############################
# NVIDIA + WAYLAND ENV VARS
############################
env = XDG_SESSION_TYPE,wayland
env = WLR_NO_HARDWARE_CURSORS,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = MOZ_ENABLE_WAYLAND,1
env = QT_QPA_PLATFORM,wayland
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

############################
# MONITOR
############################
monitor=,preferred,auto,1

############################
# AUTOSTART
############################
exec-once = waybar
exec-once = awww-daemon
exec-once = dunst
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
############################
# INPUT
############################
input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = true
        tap-to-click = true
        drag_lock = true
    }
    sensitivity = 0
}

############################
# GENERAL
############################
general {
    gaps_in = 5
    gaps_out = 12
    border_size = 2
    col.active_border = rgba(cba6f7ff) rgba(89b4faff) 45deg
    col.inactive_border = rgba(313244aa)
    layout = dwindle
}

############################
# DECORATION
############################
decoration {
    rounding = 10

    blur {
        enabled = true
        size = 6
        passes = 2
    }

    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba(00000088)
    }
}
############################
# ANIMATIONS
############################
animations {
    enabled = yes
    animation = windows,1,4,default
    animation = fade,1,3,default
    animation = workspaces,1,4,default
}

############################
# KEYBINDS FILE
############################
source = ~/.config/hypr/keybinds.conf


