$mod = SUPER

# Apps
bind = $mod, Return, exec, wezterm
bind = $mod, D, exec, wofi --show drun
bind = $mod, E, exec, dolphin
bind = $mod, Q, killactive
bind = $mod, M, exit
bind = $mod, F, fullscreen, 0
bind = $mod, V, togglefloating

# Movement
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

# Workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5

#resising the floating windows
bind = $mod CTRL, left, resizeactive, -40 0
bind = $mod CTRL, right, resizeactive, 40 0
bind = $mod CTRL, up, resizeactive, 0 -40
bind = $mod CTRL, down, resizeactive, 0 40

#moving the floating windows
bind = $mod CTRL SHIFT, left, movewindow, l
bind = $mod CTRL SHIFT, right, movewindow, r
bind = $mod CTRL SHIFT, up, movewindow, u
bind = $mod CTRL SHIFT, down, movewindow, d

# Move windows
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3

# Volume controls (FIXED)
bindl  = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

# Brightness
bindel = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Screenshot (Print Screen)
bind = , Print, exec, grim -g "$(slurp)" - | tee ~/Pictures/screenshot.png | wl-copy
